services:
  postgres:
    container_name: example-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4ssw0rd!
      POSTGRES_DB: example
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - example-postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  example-postgres:
